add missing product lookup allow macos tests to fail for bbr-s3-config-validator

diff --git a/bin/download b/bin/download
--- a/bin/download
+++ b/bin/download
@@ -14,6 +14,11 @@ trap 'rm -rf "${download_dir}"' EXIT
 
 . "${script_dir}/../products.inc.sh" "${file_name}" "${version}" "${os}"
 
+if [[ ${MISSING_PRODUCTS[*]} =~ "${file_name}_${os}" ]]; then
+  echo -e "\nError message: ${file_name} is not available for OS type ${os}\n" >&2
+  exit 1
+fi
+
 function extract_and_move() {
   local -r downloaded_file="$1"
 
