Refactoring:
- Make it easier to introduce new products: As long as products come
  from github, it only needs changing in one file, the `products.inc.sh`
- Fix some shellcheck issues
- Make it (subjectively) more readable

diff --git a/bin/download b/bin/download
--- a/bin/download
+++ b/bin/download
@@ -12,104 +12,70 @@ readonly asdf_download_path=$ASDF_DOWNLOAD_PATH
 readonly download_dir="$(mktemp -d -t "asdf_${file_name}_XXXXXXXX")"
 trap 'rm -rf "${download_dir}"' EXIT
 
-# To add a product create a case statement matching the file name and add variables as follows
-  # github_repo_path
-  # is the user/repository as taken from the github URL
-  # e.g the part in caps: https://github.com/CONCOURSE/CONCOURSE
-
-  # git_file_name_template
-  # the release file link template
-  # e.g what appears after the trailing slash: https://github.com/${github_repo_path}/releases/download/
-  # For v7.0.0/fly-7.0.0-linux-amd64.tgz would be v${version}/fly-${version}-${os}-amd64.tgz
-
-case $file_name in
-  bosh)
-    readonly github_repo_path=cloudfoundry/bosh-cli
-    readonly git_file_name_template="v${version}/bosh-cli-${version}-${os}-amd64"
-    ;;
-  credhub)
-    readonly github_repo_path=cloudfoundry-incubator/credhub-cli
-    readonly git_file_name_template="${version}/credhub-${os}-${version}.tgz"
-    ;;
-  fly)
-    readonly github_repo_path=concourse/concourse
-    readonly git_file_name_template="v${version}/fly-${version}-${os}-amd64.tgz"
-    ;;
-  om)
-    readonly github_repo_path=pivotal-cf/om
-    readonly git_file_name_template="${version}/om-${os}-${version}"
-    ;;
-  pivnet)
-    readonly github_repo_path=pivotal-cf/pivnet-cli
-    readonly git_file_name_template="v${version}/pivnet-${os}-amd64-${version}"
-    ;;
-  bbr)
-    readonly github_repo_path=cloudfoundry-incubator/bosh-backup-and-restore
-    readonly git_file_name_template="v${version}/bbr-${version}-${os}-amd64"
-    ;;
-  bbr-s3-config-validator)
-    readonly github_repo_path=cloudfoundry-incubator/bosh-backup-and-restore
-    readonly git_file_name_template="v${version}/bbr-s3-config-validator-${version}-${os}-amd64"
-    ;;
-  *)
-    echo "Product ${file_name} is not currently supported"
-    exit 1
-    ;;
-esac
+. "${script_dir}/../products.inc.sh" "${file_name}" "${version}" "${os}"
 
 function extract_and_move() {
+  local -r downloaded_file="$1"
 
-  local -r downloaded_file=$1
-
-  if [[ $git_file_name_template == *".tar.gz" ]] || [[ $git_file_name_template == *".tgz" ]]; then
-    echo "Extracting tar for $file_name"
-    tar xvfz $downloaded_file -C $download_dir/ > /dev/null
-    move_largest_file $downloaded_file
-  elif [[ ${git_file_name_template} == *".gz" ]]; then
-    echo "Extracting gunzip for $file_name"
-    gzip -dc ${downloaded_file} > ${asdf_download_path}/${file_name}
-  elif [[ ${git_file_name_template} == *".zip" ]]; then
-    echo "Extracting zip for $file_name"
-    unzip ${downloaded_file} -d ${download_dir} #> /dev/null
-    move_largest_file $downloaded_file
-  else
-    mv $downloaded_file ${asdf_download_path}/${file_name}
-  fi
+  case "$GIT_FILE_NAME_TEMPLATE" in
+    *.tar.gz|*.tgz)
+      echo "Extracting tar for ${file_name}"
+      tar xvfz "${downloaded_file}" -C "${download_dir}/" > /dev/null
+      move_largest_file "${downloaded_file}"
+      ;;
+    *.gz)
+      echo "Extracting gzip for ${file_name}"
+      gzip -dc "${downloaded_file}" > "${asdf_download_path}/${file_name}"
+      ;;
+    *.zip)
+      echo "Extracting zip for ${file_name}"
+      unzip "${downloaded_file}" -d "${download_dir}" #> /dev/null
+      move_largest_file "${downloaded_file}"
+      ;;
+    *)
+      mv "${downloaded_file}" "${asdf_download_path}/${file_name}"
+      ;;
+  esac
 }
 
 function move_largest_file() {
-  local -r downloaded_file=$1
-  rm $downloaded_file
+  local -r downloaded_file="$1"
+  rm "${downloaded_file}"
 
-  # Select the largest extracted file starting with file_name 
-  extracted_file="$(ls -d -1 ${download_dir}/${file_name}* |head -n 1)"
+  # Select the largest extracted file starting with file_name
+  extracted_file="$( ls -d -1 "${download_dir}/${file_name}"* | head -n 1 )"
 
   # if tar/zip outputs a directory, select the largest file as the target
   if [[ -d ${extracted_file} ]]; then
-    extracted_file=$(ls -Sd -1 ${extracted_file}/* |head -n 1)
+    extracted_file="$( ls -Sd -1 "${extracted_file}/"* | head -n 1 )"
   fi
 
-  mv $extracted_file ${asdf_download_path}/${file_name}
+  mv "${extracted_file}" "${asdf_download_path}/${file_name}"
 }
 
 function download_binary() {
-  local -r github_url="https://github.com/${github_repo_path}/releases/download/$git_file_name_template"
+  local -r github_url="https://github.com/${REPO_SLUG}/releases/download/${GIT_FILE_NAME_TEMPLATE}"
   local -r downloaded_file="${download_dir}/${file_name}_download"
 
-  # Validate HTTP 200 OK on download by checking headers only
-  # This enables failure handling whilst also printing download progress
-  local return=0 && check="$(curl --fail -L --head --connect-timeout 10 $github_url 2>&1)" || return="$?"
-  if [[ $return -eq 0 ]]; then
-    echo "Downloading $file_name version $version"
-    curl -L --output $downloaded_file $github_url
-    extract_and_move $downloaded_file
-  else
-    local -r error_message=$(curl --silent -L $github_url 2>&1)
-    echo "ERROR: Failure download $file_name version $version" >&2
-    echo "Attempted URL: $github_url" >&2
-    echo "Error message: $error_message" >&2
-    exit 1
+  local curl_args=(
+    -L -s --fail
+    --output "$downloaded_file"
+  )
+  if [ -n "${GITHUB_API_TOKEN:-}" ]; then
+    curl_args+=( -H "Authorization: token ${GITHUB_API_TOKEN}" )
   fi
+
+  local response ret=0
+  response="$( curl "${curl_args[@]}" "$github_url" )" || ret=$?
+
+  if [[ $ret -ne 0 ]]; then
+    echo "ERROR: Failure to download ${file_name}"
+    echo "  Return code: ${ret}"
+    echo "  Response: ${response}"
+    return $ret
+  fi >&2
+
+  extract_and_move "${downloaded_file}"
 }
 
 download_binary
diff --git a/bin/list-all b/bin/list-all
--- a/bin/list-all
+++ b/bin/list-all
@@ -7,64 +7,31 @@ set -euo pipefail
 readonly script_dir="$( cd -P "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
 readonly file_name="$(basename "$(dirname "${script_dir}")")"
 
-# To add a product create a case statement matching the file name and add variables as follows
-  # github_repo_path
-  # is the user/repository as taken from the github URL
-  # e.g the part in caps: https://github.com/CONCOURSE/CONCOURSE
-
-case $file_name in
-  bosh)
-    readonly github_repo_path=cloudfoundry/bosh-cli
-    ;;
-  credhub)
-    readonly github_repo_path=cloudfoundry-incubator/credhub-cli
-    ;;
-  fly)
-    readonly github_repo_path=concourse/concourse
-    ;;
-  om)
-    readonly github_repo_path=pivotal-cf/om
-    ;;
-  pivnet)
-    readonly github_repo_path=pivotal-cf/pivnet-cli
-    ;;
-  bbr)
-    readonly github_repo_path=cloudfoundry-incubator/bosh-backup-and-restore
-    ;;
-  bbr-s3-config-validator)
-    readonly github_repo_path=cloudfoundry-incubator/bosh-backup-and-restore
-    ;;
-  *)
-    echo "Product ${file_name} is not currently supported"
-    exit 1
-    ;;
-esac
+. "${script_dir}/../products.inc.sh" "${file_name}"
 
 function list_all() {
-  local curl_response
-  local versions
-  local -r github_url="https://api.github.com/repos/${github_repo_path}/releases"
-
-  local curl_cmd="curl -Ls"
+  local github_url="https://api.github.com/repos/${REPO_SLUG}/releases"
+  local curl_args=( -L -s --fail )
   if [ -n "${GITHUB_API_TOKEN:-}" ]; then
-    curl_cmd="$curl_cmd -H 'Authorization: token $GITHUB_API_TOKEN'"
+    curl_args+=( -H "Authorization: token ${GITHUB_API_TOKEN}" )
   fi
 
-  local ret=0 && curl_response=$(eval "$curl_cmd --fail $github_url" 2>&1) || ret="$?"
-  if [[ $ret -eq 0 ]]; then
-    # Fetch all tag names, and get only second column. Then remove all unnecesary characters.
-    versions=$(echo $curl_response | grep -oE "tag_name\": *\".{1,15}\"," | sed 's/tag_name\": *\"//;s/\",//; 's/v//g'' | \
-      LC_ALL=C sort -t. -k 1,1 -k 2,2n -k 3,3n -k 4,4n -k 5,5n)
-    echo $versions
+  local curl_response ret=0
+  curl_response="$( curl "${curl_args[@]}" "$github_url" 2>&1 )" || ret="$?"
 
-  else
-    local error=$(eval "$curl_cmd $github_url" 2>&1)
-    echo "ERROR: Failure to collect versions for $file_name"
-    echo "Error message: $error"
-    exit 1
+  if [[ $ret -ne 0 ]]; then
+    echo "ERROR: Failure to collect versions for ${file_name}"
+    echo "  Return code: ${ret}"
+    echo "  Response: ${curl_response}"
+    return $ret
+  fi >&2
 
-  fi
-
+  # Fetch all tag names, and get only second column. Then remove all unnecesary characters.
+  echo "$curl_response" \
+    | grep -oE 'tag_name": *".{1,15}",' \
+    | sed 's/tag_name": *"// ; s/",// ; s/v//g' \
+    | LC_ALL=C sort -t. -k 1,1 -k 2,2n -k 3,3n -k 4,4n -k 5,5n \
+    | xargs
 }
 
 list_all
