refactor testing to external scripts add error handling to list-all add local tests via docker

diff --git a/bin/list-all b/bin/list-all
--- a/bin/list-all
+++ b/bin/list-all
@@ -42,12 +42,12 @@ case $file_name in
     ;;
 esac
 
-# borrowed from https://github.com/rbenv/ruby-build/pull/631/files#diff-fdcfb8a18714b33b07529b7d02b54f1dR942
-function sort_versions() {
-  sed 'h; s/[+-]/./g; s/.p\([[:digit:]]\)/.z\1/; s/$/.z/; G; s/\n/ /' | \
-    LC_ALL=C sort -t. -k 1,1 -k 2,2n -k 3,3n -k 4,4n -k 5,5n | \
-    awk '{print $2}'
-}
+# # borrowed from https://github.com/rbenv/ruby-build/pull/631/files#diff-fdcfb8a18714b33b07529b7d02b54f1dR942
+# function sort_versions() {
+#   sed 'h; s/[+-]/./g; s/.p\([[:digit:]]\)/.z\1/; s/$/.z/; G; s/\n/ /' | \
+#     LC_ALL=C sort -t. -k 1,1 -k 2,2n -k 3,3n -k 4,4n -k 5,5n | \
+#     awk '{print $2}'
+# }
 
 function list_all() {
   local versions
@@ -58,10 +58,9 @@ function list_all() {
   if [ -n "${GITHUB_API_TOKEN:-}" ]; then
     curl_cmd="$curl_cmd -H 'Authorization: token $GITHUB_API_TOKEN'"
   fi
-  curl_cmd="$curl_cmd $github_url"
 
   
-  ret=0 && curl_response=$(eval "$curl_cmd" 2>&1) || ret="$?"
+  ret=0 && curl_response=$(eval "$curl_cmd --fail $github_url" 2>&1) || ret="$?"
   if [[ $ret -eq 0 ]]; then
     # Fetch all tag names, and get only second column. Then remove all unnecesary characters.
     versions=$(echo $curl_response | grep -oE "tag_name\": *\".{1,15}\"," | sed 's/tag_name\": *\"//;s/\",//; 's/v//g'' | \
@@ -69,8 +68,9 @@ function list_all() {
     echo $versions
 
   else
+    error=$(eval "$curl_cmd $github_url" 2>&1)
     echo "ERROR: Failure to collect versions for $file_name"
-    echo "Error message: $curl_response"
+    echo "Error message: $error"
     exit 1
 
   fi
